version: '3'

services:
#  kafka01.internal-service:
#    image: spotify/kafka
#    ports:
#      - "9092:9092"
#      - "2181:2181"
#    hostname: kafka01.internal-service
#    environment:
#      ADVERTISED_HOST_NAME: kafka01.internal-service
#      ADVERTISED_PORT: 9092
#      KAFKA_VERSION: 0.11.0.2
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    ports:
      - '2181:2181'
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
          default:
            aliases:
              - zookeeper.internal-service
  kafka01.internal-service:
    image: confluentinc/cp-kafka:4.1.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01.internal-service:9092
  kafka02.internal-service:
    image: confluentinc/cp-kafka:4.1.0
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02.internal-service:9093
  kafka03.internal-service:
    image: confluentinc/cp-kafka:4.1.0
    depends_on:
      - zookeeper
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03.internal-service:9094
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    hostname: kafka-manager.internal-service
    environment:
      ZK_HOSTS: zookeeper.internal-service:2181
      APPLICATION_SECRET: littlepig-letmein
      KM_VERSION: 1.3.3.17
    depends_on:
      - zookeeper
      - kafka01.internal-service
