version: '3'

services:
  kafka01.internal-service:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka01.internal-service
    environment:
      ADVERTISED_HOST_NAME: kafka01.internal-service
      ADVERTISED_PORT: 9092
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    hostname: kafka-manager.internal-service
    environment:
      ZK_HOSTS: kafka01.internal-service:2181
      APPLICATION_SECRET: littlepig-letmein
      KM_VERSION: 1.3.3.17
    depends_on:
      - kafka01.internal-service
